# Exemplo de uso do bloco try-except em Python

try:
    print(x)
except:
    print("Ocorreu um exceção")
